version: 1
disable_existing_loggers: false

formatters:
  # Единый JSON форматтер для всех
  json:
    format: '{"level": "%(levelname)s", "timestamp": "%(asctime)s", "logger": "%(name)s", "lineno": %(lineno)d, "message": "%(message)s"}'
    datefmt: "%Y-%m-%dT%H:%M:%S%z"

handlers:
  # Единый обработчик для вывода в stdout
  default:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    stream: ext://sys.stdout

loggers:
  root:
    level: INFO
    handlers: [default]
    propagate: false
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: false
  uvicorn.access:
    level: WARNING
    handlers: [default]
    propagate: false