"""empty message

Revision ID: 3708d1e51e27
Revises: 01829617eac0
Create Date: 2025-07-20 00:45:02.200679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3708d1e51e27'
down_revision: Union[str, Sequence[str], None] = '01829617eac0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('currency', 'sign',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               existing_nullable=False)
    op.drop_constraint(op.f('currency_name_key'), 'currency', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('currency_name_key'), 'currency', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('currency', 'sign',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('currency', 'name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
